---
language: python
python: "2.7"

branches:
  only:
    - master
    - dev

# Use the new container infrastructure
sudo: required

virtualenv:
  system_site_packages: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip
    - python-apt

before_install:
  - sudo apt-get purge pgdg-keyring
  - sudo apt-get autoremove
  - sudo rm -rf /var/lib/postgresql
  - sudo rm -rf /etc/postgresql
  - sudo rm /etc/apt/sources.list.d/pgdg-source.list

install:
  # Install ansible
  - pip install ansible

script:
  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --become
