---
- name: TCP/IP support - ip
  lineinfile:
    dest: /etc/postgresql/{{ pgsql_version }}/main/postgresql.conf
    regexp: "^listen_addresses"
    line: "listen_addresses = '{{ pgsql_listen_address }}'"
    owner: postgres
    group: postgres
    backup: yes
  notify: restart postgresql
  when: pgsql_tcpip_enable

- name: TCP/IP support - port
  lineinfile:
    dest: /etc/postgresql/{{ pgsql_version }}/main/postgresql.conf
    regexp: "^port"
    line: "port = '{{ pgsql_listen_port }}'"
    owner: postgres
    group: postgres
    backup: yes
  notify: restart postgresql
  when: pgsql_tcpip_enable

- name: Update pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/{{ pgsql_version }}/main/pg_hba.conf
    owner: postgres
    group: postgres
    backup: yes
  notify: restart postgresql
