---
- name: postgreSQL | create su
  postgresql_user:
    name={{ psql_remote_user }}
    password={{ psql_remote_pass }}
    become: yes
    become_user: postgres
    become_method: su

- name: postgreSQL | create DB for new su
  postgresql_db:
    name={{ psql_remote_db }}
    owner="{{ psql_remote_user }}"
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'
    template='template0'
    become: yes
    become_user: postgres
    become_method: su

- name: postgreSQL | copy new pg_hba.conf
  template:
    src=pg_hba.conf.j2
    dest=/etc/postgresql/9.4/main/
    backup=yes
  notify: restart postgresql
