---
# Getting version of the postgresql
- shell: psql -V | cut -d' ' -f 3 | cut -d '.' -f 1,2
  register: psql_version

- name: postgreSQL | create user
  sudo_user: postgres
  postgresql_user:
    name={{ psql_remote_user }}
    password={{ psql_remote_pass }}
    role_attr_flags=SUPERUSER

- name: postgreSQL | create DB for new user
  sudo_user: postgres
  postgresql_db:
    name={{ psql_remote_db }}
    owner="{{ psql_remote_user }}"
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'
    template='template0'

- name: postgreSQL | copy new pg_hba.conf
  template:
    src=pg_hba.conf.j2
    dest=/etc/postgresql/{{ item }}/main/pg_hba.conf
    backup=yes
  with_items: psql_version.stdout_lines

- name: postgreSQL | copy postgresql.conf
  notify: restart postgresql
  copy:
    src=postgresql.conf
    dest=/etc/postgresql/{{ item }}/main/postgresql.conf
    backup=yes
  with_items: psql_version.stdout_lines
