---
- name: Create user
  sudo_user: postgres
  postgresql_user:
    name: "{{ pgsql_user_name }}"
    password: "{{ pgsql_user_password }}"
    role_attr_flags: "{{ pgsql_user_priv }}"

- name: Create database for user
  sudo_user: postgres
  postgresql_db:
    name: "{{ pgsql_user_name }}"
    owner: "{{ pgsql_user_db }}"
    encoding: "{{ pgsql_encoding }}"
    lc_collate: "{{ pgsql_locale }}"
    lc_ctype: "{{ pgsql_locale }}"
    template: "{{ pgsql_template }}"
