---
# file: handlers/main.yml

# for debian
- name: restart postgresql_Debian
  service:
    name: "{{ psql_service_name }}"
    state: restarted

# for ubuntu
- name: restart postgresql_Ubuntu
  service:
    name: "{{ psql_service_name }}"
    state: restarted
  args: "{{ psql_version }}/main"
